#include "config.h"
#include "web_server.h"
#include "command.h"
#include <WiFi.h>

WebServer server(80);

static void httpRoot() {
  String ip = WiFi.localIP().toString();
  String html = String(
    "<!doctype html><html lang='zh'><head><meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'>"
    "<meta name='theme-color' content='#0b1120'>"
    "<title>灯光控制</title>"
    "<style>"
    "*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}"
    "html,body{height:100%}"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif;"
    "background:radial-gradient(ellipse at top,#1e293b,#0b1120 60%);color:#e2e8f0;"
    "min-height:100vh;padding:16px;max-width:520px;margin:0 auto;overflow-x:hidden}"
    ".hdr{text-align:center;padding:14px 0 8px}"
    ".hdr h1{font-size:24px;font-weight:700;background:linear-gradient(135deg,#22d3ee,#a78bfa,#f472b6);"
    "-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;letter-spacing:.5px}"
    ".hdr .sub{font-size:12px;color:#64748b;margin-top:6px;display:flex;align-items:center;justify-content:center;gap:8px}"
    ".dot{width:6px;height:6px;border-radius:50%;background:#22c55e;box-shadow:0 0 8px #22c55e;animation:pulse 2s infinite}"
    "@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}"
    ".hdr .ip{font-size:11px;color:#475569;margin-top:4px;font-family:ui-monospace,monospace}"
    ".card{background:rgba(30,41,59,.55);border:1px solid rgba(148,163,184,.08);"
    "border-radius:20px;padding:18px;margin-bottom:14px;backdrop-filter:blur(16px);"
    "box-shadow:0 8px 32px rgba(0,0,0,.25),inset 0 1px 0 rgba(255,255,255,.04)}"
    ".card h3{font-size:12px;font-weight:600;color:#94a3b8;margin-bottom:14px;"
    "text-transform:uppercase;letter-spacing:1.5px;display:flex;align-items:center;gap:8px}"
    ".card h3::before{content:'';width:4px;height:14px;background:linear-gradient(180deg,#22d3ee,#a78bfa);border-radius:2px}"
    ".led-preview{width:100%;height:120px;border-radius:16px;margin-bottom:16px;"
    "background:#0f172a;position:relative;overflow:hidden;border:1px solid rgba(148,163,184,.1)}"
    ".led-preview .glow{position:absolute;inset:0;background:radial-gradient(ellipse at center,var(--c,rgba(34,211,238,.4)),transparent 70%);"
    "transition:background .2s}"
    ".led-preview .val{position:absolute;bottom:10px;right:12px;font-family:ui-monospace,monospace;"
    "font-size:11px;color:#94a3b8;letter-spacing:.5px}"
    ".rgb-wrap{display:flex;flex-direction:column;gap:12px}"
    ".rgb-row{display:flex;align-items:center;gap:10px}"
    ".rgb-lab{width:22px;font-size:11px;font-weight:700;text-align:center;border-radius:6px;"
    "padding:4px 0;color:#fff;font-family:ui-monospace,monospace}"
    ".rgb-lab.r{background:linear-gradient(135deg,#ef4444,#dc2626)}"
    ".rgb-lab.g{background:linear-gradient(135deg,#22c55e,#16a34a)}"
    ".rgb-lab.b{background:linear-gradient(135deg,#3b82f6,#2563eb)}"
    ".rgb-lab.w{background:linear-gradient(135deg,#f59e0b,#d97706)}"
    ".rgb-num{width:44px;text-align:right;font-family:ui-monospace,monospace;font-size:13px;color:#cbd5e1;font-weight:600}"
    "input[type=range].rgb{-webkit-appearance:none;flex:1;height:28px;border-radius:14px;"
    "outline:none;background:transparent;position:relative}"
    "input[type=range].rgb::-webkit-slider-runnable-track{height:6px;border-radius:3px;"
    "background:linear-gradient(90deg,#1e293b 0%,var(--tc) 100%)}"
    "input[type=range].rgb::-webkit-slider-thumb{-webkit-appearance:none;width:22px;height:22px;"
    "border-radius:50%;background:#fff;cursor:pointer;margin-top:-8px;"
    "box-shadow:0 2px 10px rgba(0,0,0,.4),0 0 0 3px rgba(255,255,255,.1)}"
    ".quick-colors{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:14px}"
    ".qc{height:32px;border-radius:10px;border:none;cursor:pointer;transition:transform .12s,box-shadow .2s;"
    "background:var(--c);box-shadow:0 2px 8px rgba(0,0,0,.3)}"
    ".qc:active{transform:scale(.9)}"
    ".qc.off{background:#334155;border:1px solid #475569;color:#cbd5e1;font-size:12px}"
    ".fx-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}"
    ".fx{padding:14px 10px;border-radius:12px;border:1px solid rgba(148,163,184,.12);background:#0f172a;"
    "color:#cbd5e1;font-size:14px;font-weight:600;cursor:pointer;transition:all .15s;display:flex;"
    "align-items:center;justify-content:center;gap:8px}"
    ".fx:active{transform:scale(.96)}"
    ".fx.on{border-color:#22d3ee;background:linear-gradient(135deg,rgba(34,211,238,.18),rgba(167,139,250,.14));color:#fff;"
    "box-shadow:0 0 0 1px rgba(34,211,238,.4),0 4px 16px rgba(34,211,238,.15)}"
    ".tft-text input{width:100%;padding:12px 14px;border-radius:12px;border:1px solid rgba(148,163,184,.15);"
    "background:#0f172a;color:#e2e8f0;font-size:15px;outline:none;margin-bottom:10px}"
    ".tft-text input:focus{border-color:#22d3ee}"
    ".tft-row{display:flex;gap:10px}"
    ".tft-row select{background:#0f172a;color:#cbd5e1;border:1px solid rgba(148,163,184,.15);border-radius:12px;"
    "padding:0 12px;font-size:14px;outline:none}"
    ".tbtn{flex:1;padding:12px;border-radius:12px;border:1px solid rgba(148,163,184,.15);background:#0f172a;"
    "color:#cbd5e1;font-size:14px;font-weight:600;cursor:pointer;transition:all .15s}"
    ".tbtn:active{transform:scale(.97)}"
    ".tbtn.send{background:linear-gradient(135deg,#22d3ee,#a78bfa);color:#0b1120;border:none}"
    ".tft-fill{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:14px 0}"
    ".sc{height:36px;border-radius:10px;border:1px solid rgba(148,163,184,.12);cursor:pointer;background:var(--c);"
    "box-shadow:0 2px 8px rgba(0,0,0,.3);transition:transform .12s}"
    ".sc:active{transform:scale(.9)}"
    ".tft-row2{display:flex;gap:10px}"
    ".status-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:12px}"
    ".status-item{background:#0f172a;border-radius:10px;padding:10px 12px;border:1px solid rgba(148,163,184,.06)}"
    ".status-item .k{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px}"
    ".status-item .v{font-family:ui-monospace,monospace;font-size:13px;color:#e2e8f0;font-weight:500;word-break:break-all}"
    ".status-item .v.good{color:#22c55e}"
    ".status-item .v.warn{color:#f59e0b}"
    "</style></head><body>"
    "<div class='hdr'>"
    "<h1>灯光控制</h1>"
    "<div class='sub'><span class='dot'></span><span>Kimi Robot 在线</span></div>"
    "<div class='ip'>") + ip + String("</div>"
    "</div>"

    "<div class='card'>"
    "<h3>颜色</h3>"
    "<div class='led-preview' id='lp'><div class='glow' id='lg'></div><div class='val' id='lv'>RGB(0,150,136)</div></div>"
    "<div class='rgb-wrap'>"
    "<div class='rgb-row'><span class='rgb-lab r'>R</span>"
    "<input type='range' class='rgb' id='r' min='0' max='255' value='0' style='--tc:#ef4444' oninput='updLED()'>"
    "<span class='rgb-num' id='rv'>0</span></div>"
    "<div class='rgb-row'><span class='rgb-lab g'>G</span>"
    "<input type='range' class='rgb' id='g' min='0' max='255' value='150' style='--tc:#22c55e' oninput='updLED()'>"
    "<span class='rgb-num' id='gv'>150</span></div>"
    "<div class='rgb-row'><span class='rgb-lab b'>B</span>"
    "<input type='range' class='rgb' id='b' min='0' max='255' value='136' style='--tc:#3b82f6' oninput='updLED()'>"
    "<span class='rgb-num' id='bv'>136</span></div>"
    "</div>"
    "<div class='quick-colors'>"
    "<button class='qc' style='--c:#ef4444' onclick=\"setLED(255,0,0)\"></button>"
    "<button class='qc' style='--c:#f97316' onclick=\"setLED(249,115,22)\"></button>"
    "<button class='qc' style='--c:#eab308' onclick=\"setLED(234,179,8)\"></button>"
    "<button class='qc' style='--c:#22c55e' onclick=\"setLED(34,197,94)\"></button>"
    "<button class='qc' style='--c:#3b82f6' onclick=\"setLED(59,130,246)\"></button>"
    "<button class='qc' style='--c:#a855f7' onclick=\"setLED(168,85,247)\"></button>"
    "<button class='qc' style='--c:#ec4899' onclick=\"setLED(236,72,153)\"></button>"
    "<button class='qc' style='--c:#14b8a6' onclick=\"setLED(20,184,166)\"></button>"
    "<button class='qc' style='--c:#f8fafc' onclick=\"setLED(255,255,255)\"></button>"
    "<button class='qc off' onclick=\"setLED(0,0,0)\">关</button>"
    "</div>"
    "</div>"

    "<div class='card'>"
    "<h3>亮度</h3>"
    "<div class='rgb-row'><span class='rgb-lab w'>%</span>"
    "<input type='range' class='rgb' id='br' min='0' max='100' value='78' style='--tc:#f59e0b' oninput='updBright()'>"
    "<span class='rgb-num' id='brv'>78</span></div>"
    "</div>"

    "<div class='card'>"
    "<h3>灯效</h3>"
    "<div class='fx-grid'>"
    "<button class='fx on' id='fx-SOLID' onclick=\"setFx('SOLID')\">● 常亮</button>"
    "<button class='fx' id='fx-BREATHE' onclick=\"setFx('BREATHE')\">◐ 呼吸</button>"
    "<button class='fx' id='fx-RAINBOW' onclick=\"setFx('RAINBOW')\">◈ 彩虹</button>"
    "<button class='fx' id='fx-BLINK' onclick=\"setFx('BLINK')\">◇ 闪烁</button>"
    "</div>"
    "</div>"

    "<div class='card'>"
    "<h3>舵机</h3>"
    "<div class='rgb-row'><span class='rgb-lab w'>°</span>"
    "<input type='range' class='rgb' id='sv' min='0' max='180' value='90' style='--tc:#22d3ee' oninput='updServo()'>"
    "<span class='rgb-num' id='svv'>90</span></div>"
    "<div class='tft-row2' style='margin-top:12px'>"
    "<button class='tbtn' onclick='setServo(0)'>0°</button>"
    "<button class='tbtn' onclick='setServo(90)'>90°</button>"
    "<button class='tbtn' onclick='setServo(180)'>180°</button>"
    "<button class='tbtn' onclick='servoOff()'>松劲</button>"
    "</div>"
    "</div>"

    "<div class='card'>"
    "<h3>显示屏</h3>"
    "<div class='tft-text'>"
    "<input type='text' id='tt' maxlength='120' placeholder='输入要显示的文字...' value='你好，Kimi 机器人'>"
    "<div class='tft-row'>"
    "<select id='tsz'><option value='1'>小</option><option value='2' selected>中</option><option value='3'>大</option></select>"
    "<button class='tbtn send' onclick='sendText()'>显示文字</button>"
    "</div>"
    "</div>"
    "<div class='tft-fill'>"
    "<button class='sc' style='--c:#ef4444' onclick='fill(255,0,0)'></button>"
    "<button class='sc' style='--c:#22c55e' onclick='fill(34,197,94)'></button>"
    "<button class='sc' style='--c:#3b82f6' onclick='fill(59,130,246)'></button>"
    "<button class='sc' style='--c:#eab308' onclick='fill(234,179,8)'></button>"
    "<button class='sc' style='--c:#a855f7' onclick='fill(168,85,247)'></button>"
    "<button class='sc' style='--c:#f8fafc' onclick='fill(255,255,255)'></button>"
    "</div>"
    "<div class='tft-row2'>"
    "<button class='tbtn' onclick='rotate()'>旋转 90°</button>"
    "<button class='tbtn' onclick='clr()'>清屏</button>"
    "</div>"
    "</div>"

    "<div class='card'>"
    "<h3>设备状态</h3>"
    "<div class='status-grid'>"
    "<div class='status-item'><div class='k'>WiFi</div><div class='v' id='sw'>--</div></div>"
    "<div class='status-item'><div class='k'>IP</div><div class='v' id='si'>--</div></div>"
    "<div class='status-item'><div class='k'>BLE</div><div class='v' id='sb'>--</div></div>"
    "<div class='status-item'><div class='k'>可用内存</div><div class='v' id='sm'>--</div></div>"
    "</div>"
    "</div>"

    "<script>"
    "var ledTimer=null,brTimer=null;"
    "function $(id){return document.getElementById(id)}"
    "function get(u){return fetch(u).then(function(r){return r.text()})}"
    "function updLED(){"
    "var r=+$('r').value,g=+$('g').value,b=+$('b').value;"
    "$('rv').textContent=r;$('gv').textContent=g;$('bv').textContent=b;"
    "var c='rgb('+r+','+g+','+b+')';"
    "$('lg').style.background='radial-gradient(ellipse at center,'+c+',transparent 70%)';$('lv').textContent='RGB('+r+','+g+','+b+')';"
    "setFxUI('SOLID');"
    "clearTimeout(ledTimer);ledTimer=setTimeout(function(){get('/cmd?c='+encodeURIComponent('LED,'+r+','+g+','+b))},80)"
    "}"
    "function setLED(r,g,b){$('r').value=r;$('g').value=g;$('b').value=b;updLED()}"
    "function updBright(){var v=+$('br').value;$('brv').textContent=v;"
    "clearTimeout(brTimer);brTimer=setTimeout(function(){get('/cmd?c=BRIGHT,'+v)},80)}"
    "function setFxUI(f){['SOLID','BREATHE','RAINBOW','BLINK'].forEach(function(x){"
    "$('fx-'+x).className='fx'+(x===f?' on':'')})}"
    "function setFx(f){setFxUI(f);get('/cmd?c=FX,'+f)}"
    "var svTimer=null;"
    "function updServo(){var v=+$('sv').value;$('svv').textContent=v;"
    "clearTimeout(svTimer);svTimer=setTimeout(function(){get('/cmd?c=SERVO,'+v)},80)}"
    "function setServo(a){$('sv').value=a;updServo()}"
    "function servoOff(){get('/cmd?c=SERVO,OFF')}"
    "var tftRot=0;"
    "function sendText(){var m=$('tt').value||' ';var s=$('tsz').value;get('/cmd?c='+encodeURIComponent('TEXT,'+s+','+m))}"
    "function fill(r,g,b){get('/cmd?c='+encodeURIComponent('FILL,'+r+','+g+','+b))}"
    "function clr(){get('/cmd?c=CLEAR')}"
    "function rotate(){tftRot=(tftRot+1)%4;get('/cmd?c=ROT,'+tftRot)}"
    "function updStatus(d){"
    "$('sw').textContent=d.wifi.ssid||'--';$('sw').className='v '+(d.wifi.ssid?'good':'warn');"
    "$('si').textContent=d.wifi.ip||'--';"
    "$('sb').textContent=d.ble?'已连接':'待机';$('sb').className='v '+(d.ble?'good':'warn');"
    "if(d.heap_free!=null){$('sm').textContent=Math.round(d.heap_free/1024)+' KB'}"
    "}"
    "function syncFromDevice(d){"
    "if(d.led){$('r').value=d.led.r;$('g').value=d.led.g;$('b').value=d.led.b;"
    "$('rv').textContent=d.led.r;$('gv').textContent=d.led.g;$('bv').textContent=d.led.b;"
    "var c='rgb('+d.led.r+','+d.led.g+','+d.led.b+')';"
    "$('lg').style.background='radial-gradient(ellipse at center,'+c+',transparent 70%)';"
    "$('lv').textContent='RGB('+d.led.r+','+d.led.g+','+d.led.b+')'}"
    "if(d.bright!=null){$('br').value=d.bright;$('brv').textContent=d.bright}"
    "if(d.fx){setFxUI(d.fx)}"
    "if(d.servo&&d.servo.angle!=null){$('sv').value=d.servo.angle;$('svv').textContent=d.servo.angle}"
    "if(d.tft&&d.tft.rot!=null){tftRot=d.tft.rot}"
    "}"
    "var first=true;"
    "function loadStatus(){get('/cmd?c=STATUS').then(function(t){try{var d=JSON.parse(t);updStatus(d);if(first){syncFromDevice(d);first=false}}catch(e){}})}"
    "loadStatus();setInterval(loadStatus,4000);"
    "</script></body></html>");
  server.send(200, "text/html", html);
}

static void httpCmd() {
  if (!server.hasArg("c")) { server.send(400, "text/plain", "missing c"); return; }
  String resp = handleCommand(server.arg("c"));
  server.send(200, "text/plain", resp);
}

static void httpStatus() {
  server.send(200, "application/json", handleCommand("STATUS"));
}

void webInit() {
  server.on("/",        HTTP_GET, httpRoot);
  server.on("/cmd",     HTTP_GET, httpCmd);
  server.on("/status",  HTTP_GET, httpStatus);
  server.begin();
  Serial.println("[HTTP] Server started (port 80)");
}

void webHandleClient() {
  server.handleClient();
}
